repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-builtin-literals
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-toml
    - id: check-vcs-permalinks
    - id: check-xml
    - id: debug-statements
    - id: detect-private-key
    - id: mixed-line-ending
    - id: fix-encoding-pragma
      args: ["--remove"]
    - id: check-yaml
